#workflow
#should have name
name: Hello

#on tells when the workflow should run
on:
  workflow_dispatch: 

#jobs
#should be inside the workflow
# jobs tell what the workflow should do; there can be one or more than one jobs, hence we write jobs
# jobs is an object, so it needs indentation
jobs:
  #1st job(give indentation)
  say-hello:
    # creates an Ephemeral container with ubuntu running and delete once its executed
    runs-on: ubuntu-latest
    steps:
      - name: Say hello to everyone
        run: echo "Hello Dosto"
